import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "style/main.css";
import { Providers } from "./providers";
import { Nodes } from "types/react.types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: Nodes;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
